### ISSUE TITLE
Error message when running CTGAN evaluation

### ISSUE THREAD

**Issue by yuwenhuang717** [spring-epfl/synthetic_data_release#2]
I got a error message.
ValueError: Invalid columns found: {'columns', 'categorical_columns', 'ordinal_columns', 'continuous_columns'}
Does anyone know how to solve it?
Thanks in advance!

**Comment by laurent-girod** [comment]
Hello!

We are not sure if we already encountered this error as we do not exactly know what kind of experiment you are doing.

To help you with your issue, can you give us more info about what you are trying to run and about your experimental setup?

Also, since you mention CTGAN, it is worth mentioning Synthetic Data is using a [modified version](https://github.com/spring-epfl/CTGAN), are you using that one?

All the best!

**Comment by yuwenhuang717** [comment]
Hi!

No problems now. Many thanks for your reply!
